onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@heroui/shared-utils"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
allowBuilds:
  "@biomejs/biome": true
  "@heroui/shared-utils": true
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@lucide/astro@1.25.0'
  - astro@7.1.1
