on:
  push:
    branches:
      - master
jobs:
  setup-node:
    runs-on: docker
    container:
      image: node:23.11.0
    steps:
      - name: Check Node.js version
        run: node --version
      - name: Install pnpm globally
        run: npm install -g pnpm

  install:
    needs: setup-node
    runs-on: docker
    container:
      image: node:23.11.0
    steps:
      - name: Install dependencies
        run: pnpm install

  build:
    needs: install
    runs-on: docker
    container:
      image: node:23.11.0
    steps:
      - name: Build project
        run: pnpm build
