when:
  - event: [push]
    branch: master

steps:
  setup-node:
    image: node:23.11.0
    commands:
      - node --version
      - npm install -g pnpm

  install:
    depends_on: setup-node
    image: node:23.11.0
    commands:
      - pnpm install

  build:
    depends_on: install
    image: node:23.11.0
    commands:
      - pnpm build
