name: BFancy Astro Build & FTP Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist-path: ${{ steps.set-dist-path.outputs.dist-path }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0

      - name: Setup Node.js and cache pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro site
        run: pnpm build

      - name: Set dist path output
        id: set-dist-path
        run: echo "dist-path=dist" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: FTP Deploy dist to remote directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.SFTP_SERVER_DIR }}
          protocol: ftps
